# Generated by Django 6.0.1 on 2026-01-28 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_payments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payments',
            options={'ordering': ['-payment_date'], 'verbose_name': 'Платеж', 'verbose_name_plural': 'Платежи'},
        ),
    ]
