[tool.poetry]
name = "drf"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
pillow = "^12.1.0"
dotenv = "^0.9.9"
python-decouple = "^3.8"
djangorestframework = "^3.16.1"
django = "^6.0.1"
psycopg2-binary = "^2.9.11"
redis = "^7.1.0"
requests = "^2.32.5"
python-dotenv = "^1.2.1"
ipython = "^9.9.0"
django-filter = "^25.2"
djangorestframework-simplejwt = "^5.5.1"
coverage = "^7.13.3"
drf-yasg = "^1.21.14"
django-cors-headers = "^4.9.0"
stripe = "^14.3.0"
celery = "^5.6.2"
eventlet = "^0.40.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
